# Reemplaza con los valores exactos que te dio SonarCloud
sonar.organization=asticonsultoria
sonar.projectKey=asticonsultoria_DWW02-PRACTICA01

# Directorio de tu código fuente
sonar.sources=backend/src/main/java,frontend/src

# Archivos o carpetas a excluir
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/test/**
sonar.java.binaries=backend/target/classes