# Reemplaza con los valores exactos que te dio SonarCloud
sonar.organization=asticonsultoria
sonar.projectKey=asticonsultoria_DWW02-PRACTICA01

# Directorio de tu código fuente
sonar.sources=.

# Archivos o carpetas a excluir
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**