CREATE TABLE empleado (
    clave_prefijo VARCHAR(3) NOT NULL,
    clave_numero BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    telefono VARCHAR(100) NOT NULL,
    CONSTRAINT pk_empleado PRIMARY KEY (clave_prefijo, clave_numero)
);

CREATE INDEX idx_empleado_nombre ON empleado (nombre);
