apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: empleados-staging
type: Opaque
stringData:
  POSTGRES_USER: empleados
  POSTGRES_PASSWORD: empleados
  APP_BASIC_USER: admin
  APP_BASIC_PASSWORD: admin123
