spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/empleadosdb}
    username: ${SPRING_DATASOURCE_USERNAME:empleados}
    password: ${SPRING_DATASOURCE_PASSWORD:empleados}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

app:
  security:
    user: ${APP_BASIC_USER:admin}
    password: ${APP_BASIC_PASSWORD:admin123}
