name: Analisis de SonarCloud

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar el código (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Requerido para que Sonar analice bien las ramas y PRs

      - name: Ejecutar SonarCloud Scanner
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Lo inyecta GitHub automáticamente
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # El secreto que creaste